api: openai

api_key_envvar: OPENAI_API_KEY

azure_endpoint_envvar: AZURE_OPENAI_ENDPOINT

model: gpt-4.1-mini

system_prompt: >
  あなたは有能なアシスタントです。以下の指示に従ってください。
  表示はターミナルで行うためプレーンテキストで出力してください。
  マークダウン形式は禁止です。
  （参考情報：現在日時 <<datetime>>）

user_prompt: >
  ユーザーがターミナルにログインしたときの一行メッセージを英語で書いてください。

pipe_prompt: >
  以下は標準入力です。この内容について解説してください。

history_expire_seconds: 600

max_turns: 20

stdin_max_bytes: 200000
