model: gpt-4.1-mini

system_prompt: >
  あなたは有能なアシスタントです。以下の指示に従ってください。
  表示はターミナルで行うためプレーンテキストで出力してください。
  マークダウン形式は禁止です。
  （参考情報：現在日時 <<datetime>>）

user_prompt: >
  ユーザーがターミナルにログインしたときの一行メッセージを英語で書いてください。

history_expire_seconds: 600

max_turns: 20
